### ISSUE TITLE
Template matching sizing bug - RatEye v4.0.0

### ISSUE THREAD

**Issue by sam30606** [RatScanner/RatEye#6]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTempla
```
<details>
<summary>Log</summary>

```
[05:15:45.7388229] > [Info]  ----- RatScanner 3.6.5 -----
[05:15:45.7397363] > [Info]  Screen Info: 2560x1440 at 125%
[05:15:45.7397446] > [Info]  Setting temporary default item...
[05:15:45.7407945] > [Info]  Initializing tarkov tracker database
[05:15:45.7408954] > [Info]  Initializing hotkey manager...
[05:15:45.7438180] > [Info]  UI Ready!
[05:15:46.7529275] > [Info]  Checking for updates...
[05:15:46.7539683] > [Info]  Loading resource "RSClientVersion"...
[05:15:47.9776753] > [Info]  Loading item data...
[05:15:49.1795138] > [Info]  Loading price data...
[05:15:50.2843639] > [Info]  Loading TarkovTracker data...
[05:15:50.2843737] > [Info]  Loading TarkovTracker...
[05:15:51.7982336] > [Info]  Initializing RatEye...
[05:15:52.3664116] > [Info]  Setting up timer routines...
[05:15:52.3664311] > [Info]  Setting default item...
[05:15:52.3679891] > [Info]  Enabling hotkeys...
[05:15:52.3680201] > [Info]  Ready!
[05:20:52.3802568] > [Info]  Refreshing TarkovTracker DB...
[05:25:53.4659282] > [Info]  Refreshing TarkovTracker DB...
[05:30:54.3985991] > [Info]  Refreshing TarkovTracker DB...
[05:35:55.5534381] > [Info]  Refreshing TarkovTracker DB...
[05:40:56.4762769] > [Info]  Refreshing TarkovTracker DB...
[05:45:52.3779763] > [Info]  Refreshing Market DB...
[05:45:57.3726644] > [Info]  Refreshing TarkovTracker DB...
[05:47:52.4814639] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTemplate(InputArray templ, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass42_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0
```
</details>

**Comment by lvzekun826-coder** [comment]
Still present in RatEye 4.0.1 (via RatScanner), 2560x1440 — same assertion, same `TemplateMatchSub` frame. Note the original report is at 125% DPI and mine at 150%, which already hints that Windows DPI scaling is not the variable: what matters is `Resolution2Scale(2560, 1440) = 4/3`.
I dug into it, and it's a one-pixel rounding mismatch between three places.
**1. Templates keep their PNG size**, which `IconManager.IsValidPixelSize` constrains to `pixels % BaseSlotSize == 1` — i.e. `63 * slots + 1` px.

**2. `Icon.IconSlotSize()` truncates** when converting the captured region to slots:

```csharp
var x = (Size.X - 1) / ProcessingConfig.ScaledSlotSize;
return new Vector2((int)x, (int)y);
```

**3. `Extensions.Rescale()` truncates** when scaling the capture back to base resolution:

```csharp
var rescaledSize = new Size((int)(mat.Width * scale), (int)(mat.Height * scale));
```

At `Scale = 2560/1920 = 4/3` (`ScaledSlotSize = 84`, `InverseScale = 0.75`), a captured region of `84 * n + 1` px — which is the normal case, since a `63n+1` px icon scaled by 4/3 lands just past the slot boundary — produces:

| captured px | slots (step 2) | source px (step 3) | template px (step 1) |
|---:|:---:|---:|---:|
| 85 | 1 | 63 | 64 |
| 169 | 2 | 126 | 127 |
| 253 | 3 | 189 | 190 |
| 337 | 4 | 252 | 253 |
| 421 | 5 | 315 | 316 |

`source` ends up exactly 1px short of `templ` in both dimensions, so `Cv2.MatchTemplate` asserts. Because `TemplateMatchSub` matches inside a `Parallel.ForEach`, every icon in that slot-size bucket throws, which is why the message repeats dozens of times inside one `AggregateException`.

It is intermittent because the detected bounding box shifts by a pixel or two depending on the item and where it sits: a 170px capture rescales to 127 and matches fine, 169px does not.

**Why this is rarely reported:** `Rescale()` starts with `if (scale == 1f) return image;`. At 1920x1080 `Scale` is exactly 1, the resize is skipped entirely, and the truncation cannot happen. The bug is only reachable off 1080p — which is probably why it has sat here since 2024.

**Possible fixes**, any one of:

- round instead of truncate in `Rescale()` (`Convert.ToInt32`, which is what `PixelsToSlots` already does)
- pad or clamp `source` to at least the template size in `TemplateMatchSub()`
- skip templates larger than `source` instead of letting `Cv2.MatchTemplate` assert
- The last one alone would at least turn a hard crash into a missed match.
